# Generated by Django 5.0.3 on 2024-03-14 02:36

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_user_id_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=expenses.models.generate_user_id, max_length=5, primary_key=True, serialize=False),
        ),
    ]
